name: Auto Update Challenge

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Day Count
        run: |
          START=$(cat challenge-progress.json | grep start_date | cut -d'"' -f4)
          TODAY=$(date +%Y-%m-%d)

          START_SEC=$(date -d "$START" +%s)
          TODAY_SEC=$(date -d "$TODAY" +%s)

          DIFF=$(( (TODAY_SEC - START_SEC) / 86400 + 1 ))

          echo "Day: $DIFF" > day.txt

      - name: Commit File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update day" || echo "No change"
          git push
